---
- name: Install and configure Jenkins and Prometheus, and change MOTD
  hosts: all
  become: yes
  vars:
    username: "<username>"  # Replace with your actual username

  tasks:
    - name: Install Jenkins on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins repository on Ubuntu
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Jenkins on Ubuntu
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Jenkins on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Jenkins repository on CentOS
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        gpgcheck: yes
        enabled: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      when: ansible_os_family == "RedHat"

    - name: Install Jenkins on CentOS
      yum:
        name: jenkins
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Prometheus on Ubuntu
      apt:
        name:
          - prometheus
          - prometheus-node-exporter
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Prometheus on CentOS
      yum:
        name:
          - prometheus
          - node_exporter
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Configure Prometheus
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ['localhost:9100']  # Change this to your target hosts
      notify: Restart Prometheus

    - name: Change MOTD
      copy:
        dest: /etc/motd
        content: "Ansible Managed by {{ username }}"

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
